kind: Service
apiVersion: v1
metadata:
  name: sage-transaction-service
spec:
  type: NodePort
  selector:
    app: sage-transaction
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 5000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sage-transaction-deployment
  labels:
    app: sage-transaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sage-transaction
  template:
    metadata:
      labels:
        app: sage-transaction
    spec:
      containers:
      - name: sage-transaction
        image: redhatprabu/sage    # Consider you have pushed your image to dockerhub Repoo from task1
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sage-transaction
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sage-transaction-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
